### ISSUE TITLE
Keep downloading updated countries file

### ISSUE THREAD

**Issue by assofour** [treee111/wahooMapsCreator#10]
`            # ToDo: comment
            if len(map_files) == 1 and os.path.isfile(map_files[0]):
                file_creation_timestamp = os.path.getctime(map_files[0])
                if file_creation_timestamp < to_old_timestamp or self.force_download == 1:
                    print(f'+ mapfile for {country}: deleted')
                    os.remove(map_files[0])
                    need_to_download = True
                else:
                    border_countries[country] = {'map_file':map_files[0]}
                    print(f'+ mapfile for {country}: up-to-date')

            if len(border_countries[country]) != 1 or not os.path.isfile(border_countries[country]['map_file']):
                # if there exists no file or it is no file --> download
                need_to_download = True`

I need to download China map with many border countries, so len(border_countries[country]) != 1 will always be true and it will always download all map files over times.

**Comment by treee111** [comment]
hi!
thanks for your suggestion.
How are you starting the tool, with which country?

I gonna go into it and will hopefully correct it accordingly

**Comment by assofour** [comment]
> hi!
> thanks for your suggestion.
> How are you starting the tool, with which country?
> 
> I gonna go into it and will hopefully correct it accordingly

I am going to build map with China since I just got a Bolt V2. However I found I actually don't need all 'border countries', if there is a parameter to ignore them.

And I found another thing that 'Hong Kong' and 'Macao' are as same as China's map data, the tool downloaded 3 exactly same size file with diff filenames.

**Comment by treee111** [comment]
Hi, i released a new version: https://github.com/treee111/wahooMapsCreator/releases

Release v0.4.0 changes the download of maps from the selected country and 'border countries'.

Not maps of all countries and border-countries are downloaded if FORCE_DOWNLOAD = False.
If parameter FORCE_DOWNLOAD = False, only these maps are downloaded:
- deleted maps are downloaded
- out-of-date maps are downloaded

I would be happy if you could try this release and check if the first issue will be resolved!


Concerning the 'border countries':
These countries are needed to build the parts of the map where another country is involved.
If you think a parameter would be good to generate a country without the border-parts, I can introduce such a parameter!

I also will have a look into 3x the same maps.

I create two separate issues for these two things.

**Comment by assofour** [comment]
> Hi, i released a new version: https://github.com/treee111/wahooMapsCreator/releases
> 
> Release v0.4.0 changes the download of maps from the selected country and 'border countries'.
> 
> Not maps of all countries and border-countries are downloaded if FORCE_DOWNLOAD = False.
> If parameter FORCE_DOWNLOAD = False, only these maps are downloaded:
> 
> * deleted maps are downloaded
> * out-of-date maps are downloaded
> 
> I would be happy if you could try this release and check if the first issue will be resolved!
> 
> Concerning the 'border countries':
> These countries are needed to build the parts of the map where another country is involved.
> If you think a parameter would be good to generate a country without the border-parts, I can introduce such a parameter!
> 
> I also will have a look into 3x the same maps.
> 
> I create two separate issues for these two things.

I did tried and built map successfully, copied to Bolt V2, also works very well so far.
