### ISSUE TITLE
Introduce parameter to download only the country without border countries

### ISSUE THREAD

**Issue by treee111** [treee111/wahooMapsCreator#12]
However I found I actually don't need all 'border countries', if there is a parameter to ignore them.

from: #10

**Comment by assofour** [comment]
Let me guess, you may be from a European country, people travel across border there without any issue and quite seamlessly. In most of Asian countries, things are not like that. I believe only extreme few people in China would need border countries data. Also, it will bring in useless big country data such as Russia and India. It is absolutely impossible of a Chinese cyclist going into India by a bike.

**Comment by treee111** [comment]
yes, i'm from europe.
But you have to distinguish:
**"Raw" .osm map-files**
- These are downloaded for all border countries and are big.
- folder `common_resources/maps`

**Generated tiles for ELEMNT**
- These are only generated for tiles with zoom-level 8 of the country and border tiles, where the choosen country is involved
- Therefore, NOT all the downloaded border countries information/gigabyte are used


**Example of the tile 204/112**
- china and vietnam are one one tile
- therefore, the raw map of china and vietnam is downloaded
- To generate the part of the tile where vietnam is involved, the raw .osm map of vietnam is used
- if one would only process this tile, the output is only content of this tile, while having to download full raw files of china and vietnam
![image](https://user-images.githubusercontent.com/53038537/124224390-d92f3080-db05-11eb-97d0-6f872a85182e.png)
http://tools.geofabrik.de/map/#8/21.3445/105.8079&type=Geofabrik_Standard&grid=1

Nevertheless I got the point that downloading (not needed) border countries takes time and if one does not bike in this border areas and not crosses borders, we could only donload the choosen country-files and only process them into generated tiles.
Good point!

Does the explanation above makes sense to you?

**Comment by assofour** [comment]
Yes. It makes sense. 
In the doc QUICKSTART_MACOS.md , the title should be corrected to "Quick Start Guide for macOS".

**Comment by treee111** [comment]
Hi @assofour,
I developed that feature and published it in Version 0.5.0

you have to change parameter CALC_BORDER_COUNTRIES to False to not download the border countries:  
https://github.com/treee111/wahooMapsCreator/blob/7800fc3c1154cf6a1093dc7c638399ae96dd8dd8/wahoo_map_creator.py#L18-L19

Now you get faster processing times because you not needed countries are not downloaded.
I'm happy for any feedback, feature requests or information in the case of errors! 👍

**Comment by assofour** [comment]
@treee111 Great, will test it in next few days and get back to you.
