### ISSUE TITLE
ERROR:Error in Osmosis with sorting land* osm files of tile: 129,94

### ISSUE THREAD

**Issue by mcrobiej** [treee111/wahooMapsCreator#123]
## Expected Behavior
{That the tiles are sorted}

## Current Behavior
{Error thrown in GUI 
ERROR:Error in Osmosis with sorting land* osm files of tile: 129,94 }

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * OS/Platform: Windows 10 64 bit
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by treee111** [comment]
Hi, thanks for creating the issue!
This issue should be fixed for Windows with version 2.0.1

Which version are you using?
How have you installed wahooMapsCreator? PyPI or .zip download?

**Comment by mcrobiej** [comment]
I'll have a look at my version and get back to you - thankyou for the quick response

**Comment by mcrobiej** [comment]
Re Installed 2.0.1 and running fine from CLI . Thanks
