### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by mushroom11s** [treee111/wahooMapsCreator#130]
![image](https://user-images.githubusercontent.com/28756933/170011686-04b8566e-66f9-4027-8bb8-f8af890cfb0b.png)

2.0.1 release was not working.

**Comment by mushroom11s** [comment]
Sorry, it's because I moved the unzipped file that caused an exception. But there have another exception.


![image](https://user-images.githubusercontent.com/28756933/170156437-8a0c2541-3e9a-47d5-a4d4-5c68038a823d.png)

**Comment by mushroom11s** [comment]
My pc environment like this:
![image](https://user-images.githubusercontent.com/28756933/170160176-b5e840a9-844b-47c3-b374-bd320c16de90.png)
![image](https://user-images.githubusercontent.com/28756933/170160183-a1bceb93-8a54-44e5-8923-ea565b26957a.png)
![image](https://user-images.githubusercontent.com/28756933/170160193-b082d4c0-e9f3-47fd-8b57-1439f9cfc8db.png)
![image](https://user-images.githubusercontent.com/28756933/170160210-f26f0c98-a17c-4750-a58f-52c8151c7647.png)

**Comment by mushroom11s** [comment]
I trun to linux , it's worked. But there are some errors on windows.

**Comment by treee111** [comment]
Hi!
thanks for using the tool and writing that issue!
Based on your screenthots it seams that you are not in the Anaconda environment on Windows.
Did you follow the quickstart guide to create **and activate** the Anaconda environment?
`conda activate gdal-user`

see: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#create-anaconda-environment

**Comment by mushroom11s** [comment]
> Hi! thanks for using the tool and writing that issue! Based on your screenthots it seams that you are not in the Anaconda environment on Windows. Did you follow the quickstart guide to create **and activate** the Anaconda environment? `conda activate gdal-user`
> 
> see: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#create-anaconda-environment

Thanks ！！！I tried again. Same as you say .It's  Anaconda  environment problem.But when i exec  `conda activate gdal-user`.It's not effective. 
Anyway ，i used with linux is ok. That was great tools.Thanks for you open it.😘

**Comment by mushroom11s** [comment]
If you  come to China ,Hope cycling with you.

**Comment by mushroom11s** [comment]
If you  come to China ,Hope cycling with you.

**Comment by treee111** [comment]
> > Hi! thanks for using the tool and writing that issue! Based on your screenthots it seams that you are not in the Anaconda environment on Windows. Did you follow the quickstart guide to create **and activate** the Anaconda environment? `conda activate gdal-user`
> > see: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#create-anaconda-environment
> 
> Thanks ！！！I tried again. Same as you say .It's Anaconda environment problem.But when i exec `conda activate gdal-user`.It's not effective. Anyway ，i used with linux is ok. That was great tools.Thanks for you open it.😘

I thought about this once again:
- Are you using a "normal" cmd shell in Windows?
- If yes, the `conda` command may not be recogniced

You need to start `Anaconda Prompt` from Windows startmenu:
- and then type into the conda- command.
- What happens in both shells if you type `conda env list` - is your created environment shown?

Yay cycling in China would be nice ;-)

**Comment by mushroom11s** [comment]
> > > Hi! thanks for using the tool and writing that issue! Based on your screenthots it seams that you are not in the Anaconda environment on Windows. Did you follow the quickstart guide to create **and activate** the Anaconda environment? `conda activate gdal-user`
> > > see: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#create-anaconda-environment
> > 
> > 
> > Thanks ！！！I tried again. Same as you say .It's Anaconda environment problem.But when i exec `conda activate gdal-user`.It's not effective. Anyway ，i used with linux is ok. That was great tools.Thanks for you open it.😘
> 
> I thought about this once again:
> 
> * Are you using a "normal" cmd shell in Windows?
> * If yes, the `conda` command may not be recogniced
> 
> You need to start `Anaconda Prompt` from Windows startmenu:
> 
> * and then type into the conda- command.
> * What happens in both shells if you type `conda env list` - is your created environment shown?
> 
> Yay cycling in China would be nice ;-)

I used the ` windows terminal ` . It's default start with `powershell`.
![image](https://user-images.githubusercontent.com/28756933/170666973-b5e98310-c581-4632-88a4-c44a38633b3c.png)
![image](https://user-images.githubusercontent.com/28756933/170666988-717dc316-8976-4062-aeca-47476e204d4a.png)
It seems that this is the reason why conda didn't activate gdal-user.
I'm run in `Anaconda Prompt `,It did work.👍

**Comment by treee111** [comment]
Very nice - thanks for checking it and enjoy! :-)
If you have any questions, don't hesitate to ask! 👍
