### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by DingXing91** [treee111/wahooMapsCreator#132]
![20220604185222](https://user-images.githubusercontent.com/2527346/171995960-3524dadf-5b20-4403-b668-0d5f73321094.png)

**Comment by treee111** [comment]
Hi, thanks for using this tool and the issue!

can you fill out this please to get a feeling of your setup?
Context
 * OS/Platform: `unknown` (32 or 64 bit)
 * installation: (via PyPI or .zip)
 * Other information regarding your environment *(optional)*: `nothing`

I tried to create a workaround for this issue.
Could you please install version 2.0.2a1 via PyPI with:
`pip install wahoomc==2.0.2a1 --upgrade`

**Comment by DingXing91** [comment]
Hi treee111, I installed wahoomc on a win10 system, using Anaconda and pip.
I switched to 2.0.2a1 and the issue seems fixed.

Thanks for your fantastic tool!

[terminal.txt](https://github.com/treee111/wahooMapsCreator/files/8839436/terminal.txt)

**Comment by treee111** [comment]
Hi @DingXing91,
thanks for checking if the workaround works. 👍 

I made it more general to catch these cases.
Would be nice if you could double-check if it still works for you!
`pip install wahoomc==2.0.2a3 --upgrade`

You can also "review" via the assigned PR with the changes :-)
If that is OK, I will include the coding into the main branch and publish a new bugfix release.

Thanks in advance!

PS: Maybe the source for this - first - occurence is the encoding or language setting of your computer.

**Comment by DingXing91** [comment]
2.0.2a3 works fine too :)
