### ISSUE TITLE
Error parsing command line: unrecognised option '--remove-tags'

### ISSUE THREAD

**Issue by FarAway789** [treee111/wahooMapsCreator#134]
Hello,
Thanks a lot for building such a great tool! 
In my first use of it I am facing an error that I have no clue how to solve:

## Current Behavior
Running `python -m wahoomc cli -co malta` gives this error:

```
DEBUG:+ Read json file: OK
INFO:--------------------------------------------------------------------------------
INFO:# Determine involved/border countries
INFO:+ Involved country: malta
INFO:--------------------------------------------------------------------------------
INFO:# check land_polygons.shp file
INFO:+ check land_polygons.shp file: OK
INFO:--------------------------------------------------------------------------------
INFO:# check countries .osm.pbf files
INFO:+ Checking for old maps and remove them
INFO:+ mapfile for malta: up-to-date. Input: malta.
INFO:+ Check countries .osm.pbf files: OK
INFO:--------------------------------------------------------------------------------
INFO:# Filter tags from country osm.pbf files
INFO:+ Create filtered country file for malta
DEBUG:subprocess:"Error parsing command line: unrecognised option '--remove-tags'"
ERROR:! Error in Osmium with country: {key}
```

## Context
 * OS/Platform: linux with gdal-user environment activated and wahoomc installed with pip

Please tell me if I can provide any additional info to help understand the root cause. I suspect this may rather be linked to my installation but found no clue to solve it...

Thanks !

**Comment by treee111** [comment]
Hi!
thanks for using the tool and creating the issue 👍 
Well described issue and nice that you use the CLI, I also like it that way :-)

We'll figure that out in small steps!
Please follow them one by one, I acutally implement a prerequisite check which may be helping in cases like that :-)

1. Which version of wahooMapsCreator is installed?
go to your conda environment in terminal and then `conda list`
2. Could you please install version 2.1.0a3
still in your environment with `pip install wahoomc==2.1.0a3`
3. What is the output of these statements?
`python -m wahoomc cli -h`
`python -m wahoomc cli -co malta`

**Comment by FarAway789** [comment]
Thanks for your response !

Here it is:

I had version 2.0.2 (see conda list below)

```
conda list

# packages in environment at /home/rr_dev/.conda/envs/gdal-user:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
cairo                     1.16.0            ha12eb4b_1010    conda-forge
certifi                   2022.5.18.1              pypi_0    pypi
cfitsio                   4.1.0                hd9d235c_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
curl                      7.83.1               h2283fc2_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
gdal                      3.4.3            py37hed81ac4_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.1                h509b78c_1    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                      pypi_0    pypi
jpeg                      9e                   h166bdaf_1    conda-forge
json-c                    0.16                 hc379101_0    conda-forge
kealib                    1.4.14               hfe1a663_4    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libcurl                   7.83.1               h2283fc2_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgdal                   3.4.3                h3886835_0    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h329d8a1_102    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 h676c864_0    conda-forge
librttopo                 1.1.0                hf69c175_9    conda-forge
libspatialite             5.0.1               ha867d66_15    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0fcbabc_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzip                    1.8.0                h1c5bbd1_1    conda-forge
libzlib                   1.2.12               h166bdaf_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.3                h166bdaf_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
poppler                   22.04.0              h1434ded_1    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 hce44dc1_0    conda-forge
proj                      9.0.0                h93bde94_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.7.12          hf930737_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
setuptools                62.3.3           py37h89c1867_0    conda-forge
shapely                   1.8.2                    pypi_0    pypi
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tiledb                    2.8.3                h3f4058f_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzcode                    2022a                h166bdaf_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
wahoomc                   2.0.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_0    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge

```

Then, once 2.1.0a3 installed, I get this from the help command line:

```
python -m wahoomc cli -h
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/__main__.py", line 7, in <module>
    main.run()
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/main.py", line 30, in run
    check_installation_of_required_programs()
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/setup_functions.py", line 83, in check_installation_of_required_programs
    if not is_map_writer_plugin_installed():
  File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/setup_functions.py", line 108, in is_map_writer_plugin_installed
    for file in os.listdir(map_writer_path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/rr_dev/.openstreetmap/osmosis/plugins'
```

My osmosis is indeed installed at another location, so I had also put the plugin there:
```
> which osmosis
/usr/bin/osmosis
```

I tried putting just the jar plugin at the location looked for by the script, and also putting the whole osmosis folder at the location there (.openstreetmap/osmosis).
This now displays the help ok, but I still get the same error when generating the malta map.
I do have the "sh: 0: getcwd() failed: No such file or directory" for each command in the conda env, but then commands look to be executed ok.

```
python -m wahoomc cli -h
sh: 0: getcwd() failed: No such file or directory
usage: __main__.py cli [-h] (-co COUNTRY | -xy XY_COORDINATES) [-md MAXDAYS]
                       [-nbc] [-fd] [-fp] [-c] [-tag TAG_WAHOO_XML] [-om]
                       [-km] [-gt] [-z]

optional arguments:
  -h, --help            show this help message and exit

Primary input:
  Generate maps for...

  -co COUNTRY, --country COUNTRY
                        country to generate maps for
  -xy XY_COORDINATES, --xy_coordinates XY_COORDINATES
                        x/y coordinates to generate maps for. Example: 133/88

Options:
  Options for map generation

  -md MAXDAYS, --maxdays MAXDAYS
                        maximum age of source maps and other files
  -nbc, --bordercountries
                        do not process border countries of tiles involving
                        more than one country
  -fd, --forcedownload  force download of files
  -fp, --forceprocessing
                        force processing of files
  -c, --cruiser         save uncompressed maps for Cruiser
  -tag TAG_WAHOO_XML, --tag_wahoo_xml TAG_WAHOO_XML
                        file with tags to keep in the output
  -om, --only_merge     only merge, do no other processing
  -km, --keep_map_folders
                        keep the country and country-maps folders in the
                        output
  -gt, --geofabrik_tiles
                        calculate tiles based on geofabrik index-v1.json file
  -z, --zip             zip the country (and country-maps) folder
```

```
python -m wahoomc cli -co malta
sh: 0: getcwd() failed: No such file or directory
INFO:--------------------------------------------------------------------------------
INFO:# Input country: malta.
DEBUG:--------------------------------------------------------------------------------
DEBUG:# Read json file
DEBUG:+ Use json file /home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/resources/json/europe/malta.json with 1 tiles
DEBUG:+ Read json file: OK
INFO:--------------------------------------------------------------------------------
INFO:# Determine involved/border countries
INFO:+ Involved country: malta
INFO:--------------------------------------------------------------------------------
INFO:# check land_polygons.shp file
INFO:+ check land_polygons.shp file: OK
INFO:--------------------------------------------------------------------------------
INFO:# check countries .osm.pbf files
INFO:+ Checking for old maps and remove them
INFO:+ mapfile for malta: up-to-date. Input: malta.
INFO:+ Check countries .osm.pbf files: OK
INFO:--------------------------------------------------------------------------------
INFO:# Filter tags from country osm.pbf files
INFO:+ Create filtered country file for malta
DEBUG:subprocess:"Error parsing command line: unrecognised option '--remove-tags'"
ERROR:! Error in Osmium with country: {key}
```

So I am afraid this is just an environment on my end, but not sure what I need to change to have the script get what it needs...

**Comment by treee111** [comment]
Hey,

thanks for documenting everything so nice here :-)
I'll quote the things where I comment. The rest is fine!

> Then, once 2.1.0a3 installed, I get this from the help command line:
> 
> ```
> python -m wahoomc cli -h
> sh: 0: getcwd() failed: No such file or directory
> Traceback (most recent call last):
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/__main__.py", line 7, in <module>
>     main.run()
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/main.py", line 30, in run
>     check_installation_of_required_programs()
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/setup_functions.py", line 83, in check_installation_of_required_programs
>     if not is_map_writer_plugin_installed():
>   File "/home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/setup_functions.py", line 108, in is_map_writer_plugin_installed
>     for file in os.listdir(map_writer_path):
> FileNotFoundError: [Errno 2] No such file or directory: '/home/rr_dev/.openstreetmap/osmosis/plugins'
> ```
> 
> My osmosis is indeed installed at another location, so I had also put the plugin there:
> 
> ```
> > which osmosis
> /usr/bin/osmosis
> ```
> 
> I tried putting just the jar plugin at the location looked for by the script, and also putting the whole osmosis folder at the location there (.openstreetmap/osmosis). This now displays the help ok, but I still get the same error when generating the malta map. I do have the "sh: 0: getcwd() failed: No such file or directory" for each command in the conda env, but then commands look to be executed ok.

The path check is done statically and works for me on macOS, have no device to test on Linux.
According to https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.48#Plugin_Tasks, the plugin should be on the same directory of Linux and macOS I think.

Did you put the plugin into an other location than mentioned here initially?
https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_ANACONDA.md#macos-linux-only

As there is no other note before, osmium seams to be installed OK. The plugin is used later in the processing so that location etc. is no issue acutally in my opinion.

> ```
> python -m wahoomc cli -h
> sh: 0: getcwd() failed: No such file or directory
> usage: __main__.py cli [-h] (-co COUNTRY | -xy XY_COORDINATES) [-md MAXDAYS]
>                        [-nbc] [-fd] [-fp] [-c] [-tag TAG_WAHOO_XML] [-om]
>                        [-km] [-gt] [-z]
> 
> optional arguments:
>   -h, --help            show this help message and exit
> 
> Primary input:
>   Generate maps for...
> 
>   -co COUNTRY, --country COUNTRY
>                         country to generate maps for
>   -xy XY_COORDINATES, --xy_coordinates XY_COORDINATES
>                         x/y coordinates to generate maps for. Example: 133/88
> 
> Options:
>   Options for map generation
> 
>   -md MAXDAYS, --maxdays MAXDAYS
>                         maximum age of source maps and other files
>   -nbc, --bordercountries
>                         do not process border countries of tiles involving
>                         more than one country
>   -fd, --forcedownload  force download of files
>   -fp, --forceprocessing
>                         force processing of files
>   -c, --cruiser         save uncompressed maps for Cruiser
>   -tag TAG_WAHOO_XML, --tag_wahoo_xml TAG_WAHOO_XML
>                         file with tags to keep in the output
>   -om, --only_merge     only merge, do no other processing
>   -km, --keep_map_folders
>                         keep the country and country-maps folders in the
>                         output
>   -gt, --geofabrik_tiles
>                         calculate tiles based on geofabrik index-v1.json file
>   -z, --zip             zip the country (and country-maps) folder
> ```
> 
> ```
> python -m wahoomc cli -co malta
> sh: 0: getcwd() failed: No such file or directory
> INFO:--------------------------------------------------------------------------------
> INFO:# Input country: malta.
> DEBUG:--------------------------------------------------------------------------------
> DEBUG:# Read json file
> DEBUG:+ Use json file /home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/resources/json/europe/malta.json with 1 tiles
> DEBUG:+ Read json file: OK
> INFO:--------------------------------------------------------------------------------
> INFO:# Determine involved/border countries
> INFO:+ Involved country: malta
> INFO:--------------------------------------------------------------------------------
> INFO:# check land_polygons.shp file
> INFO:+ check land_polygons.shp file: OK
> INFO:--------------------------------------------------------------------------------
> INFO:# check countries .osm.pbf files
> INFO:+ Checking for old maps and remove them
> INFO:+ mapfile for malta: up-to-date. Input: malta.
> INFO:+ Check countries .osm.pbf files: OK
> INFO:--------------------------------------------------------------------------------
> INFO:# Filter tags from country osm.pbf files
> INFO:+ Create filtered country file for malta
> DEBUG:subprocess:"Error parsing command line: unrecognised option '--remove-tags'"
> ERROR:! Error in Osmium with country: {key}
> ```
> 
> So I am afraid this is just an environment on my end, but not sure what I need to change to have the script get what it needs...

Haven't seen this output `sh: 0: getcwd() failed: No such file or directory` before.
Was this also with version 2.0.2?
If not, it was introduced with 2.1.0a3 (what I think it is and therefore not a blocker)

I added verbose output for the command, which fails.
Could you please install 2.1.0a4 with `pip install wahoomc==2.1.0a4` and post the output, thanks!

**Comment by FarAway789** [comment]
Thank you for your help, 
 
I installed the 2.1.0a4 and get the exact same output, no additional information : 

```
...
Installing collected packages: wahoomc
  Attempting uninstall: wahoomc
    Found existing installation: wahoomc 2.1.0a3
    Uninstalling wahoomc-2.1.0a3:
      Successfully uninstalled wahoomc-2.1.0a3
Successfully installed wahoomc-2.1.0a4

python -m wahoomc cli -co malta
sh: 0: getcwd() failed: No such file or directory
INFO:--------------------------------------------------------------------------------
INFO:# Input country: malta.
DEBUG:--------------------------------------------------------------------------------
DEBUG:# Read json file
DEBUG:+ Use json file /home/rr_dev/.conda/envs/gdal-user/lib/python3.7/site-packages/wahoomc/resources/json/europe/malta.json with 1 tiles
DEBUG:+ Read json file: OK
INFO:--------------------------------------------------------------------------------
INFO:# Determine involved/border countries
INFO:+ Involved country: malta
INFO:--------------------------------------------------------------------------------
INFO:# check land_polygons.shp file
INFO:+ check land_polygons.shp file: OK
INFO:--------------------------------------------------------------------------------
INFO:# check countries .osm.pbf files
INFO:+ Checking for old maps and remove them
INFO:+ mapfile for malta: up-to-date. Input: malta.
INFO:+ Check countries .osm.pbf files: OK
INFO:--------------------------------------------------------------------------------
INFO:# Filter tags from country osm.pbf files
INFO:+ Create filtered country file for malta
DEBUG:subprocess:"Error parsing command line: unrecognised option '--remove-tags'"
ERROR:! Error in Osmium with country: {key}
```

Regarding the `sh: 0: getcwd() failed: No such file or directory` I indeed wasn't seeing it on the 2.0.2.

Thanks !

**Comment by treee111** [comment]
Thanks for your feedback. If there is no verbose output, maybe osmium is not installed correctly or the tool/conda environment can not use it as supposed.

Let's try out this in terminal to ensure, that osmium is installed OK.
1. go to a folder of your choice and try out these commands:
2. `osmium --version`
3. `osmium tags-filter --remove-tags '/home/rr_dev/wahooMapsCreatorData/_download/maps/malta-latest.osm.pbf' access area=yes bicycle bridge -o '/home/rr_dev/wahooMapsCreatorData/_tiles/filtered-malta.o5m.pbf' --overwrite -v`
  - I compiled the path to the directory `wahooMapsCreatorData` based on your outputs. May not be correct, then please adjust accordingly!

**Comment by FarAway789** [comment]
Thanks so much, indeed this was the osmium version that was too old !
I can't remember how and when I installed it, but it was the 1.7.1 in which the remove-tags option was not yet implemented.
After the upgrade to the latest version of osmium the command line works perfectly, I have been able to generate my first tiles.

Thanks for making such tool available and for your support, it was greatly appreciated !

**Comment by treee111** [comment]
puuuuh, thank you as well for replying and checking so much things!
Good that it was this easy case of a out-of-date osmium version 👍
