### ISSUE TITLE
Unclear where to copy what

### ISSUE THREAD

**Issue by r0oland** [treee111/wahooMapsCreator#136]
## Is your feature request related to a problem? Please describe.
I was able to create the maps files and connect my Wahoo to my Windows PC, but it's not clear to me what needs to be copied where.

## Describe the solution you'd like
Info on what files need to be copied.

Does the entire _tiles folder just need to be copied with all the various created files? What file types need copying, I have .o5m, .map, .map.lzma, .map.lzma.12, .dbf...
What about the folder structure etc?

**Comment by r0oland** [comment]
This is an example tiles folder, do I replaced all the content on my device in the 132 folder? So delete all and then copy new over? Or just copy over the existing and replace old files as needed?
![image](https://user-images.githubusercontent.com/558053/175803684-c196bd5e-3c00-4db4-8739-e339dcffc1d1.png)

**Comment by treee111** [comment]
Hi @r0oland,
thanks for using my tool and reporting this unclear documentation!
I gonna update it in the docs later on, here for you.

You do not need the `_tiles` directory. This is only for storage of work-in-progress files.

I dont't know if you stared with a country or with x/x coordinates, But think with a country.

You should have a directory named like your country in the `wahooMapsCreatorData` directory (see [docs](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/COPY_TO_WAHOO.md#location-of-the-generated-maps)).
The content of this folder is relevant.
In this example screenshot and we want to copy the maps of american_samoa, I would copy the folders under the `american_samoa` directory into the `maps\tiles\8` directory on the wahoo (see [docs](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/COPY_TO_WAHOO.md#copy-map-files)).
<img width="630" alt="image" src="https://user-images.githubusercontent.com/53038537/175814689-42991c5c-3faa-4019-a316-06f6fb3b0905.png">

If the folder, i.e. `6` does already exist (long form: `maps\tiles\8\6`), copy the `.map.lzma` and `.map.lzma.12` into the existing folder.

Hope this clears it up. If not, feel free to ask! 👍
