### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by zenziwerken** [treee111/wahooMapsCreator#143]
Tested under Windows 10 running in VirtualBox.

## Log Output / Stack Trace
File "C:\Users\Daniel\anaconda3\envs\gdal-user\lib\site-packages\wahoomc\osm_maps_functions.py", line 668, in create_map_files cmd.append('threads=' + threads)
TypeError: can only concatenate str (not "int") to str

## Correction could be
~~cmd.append('threads=' + threads)~~
cmd.append(f'threads={threads}')

**Comment by treee111** [comment]
Thanks for posting this issue!
I wonder why this was not reported before. I hadn't this myself running on Windows 10.

- Maybe because running in a VM is different from a "normal" OS?
  - Defaulting threads?
  - Different Python versions?

But as this is a syntax error it should be reproducable...

**Comment by zenziwerken** [comment]
Problem does not show on 'normal' Windows. Probably this line does not give suitable result in VM:
line 646: threads = str(multiprocessing.cpu_count() - 1)

Could be circumvented with a try-construction

**Comment by masc4ii** [comment]
After this line, there is an code error:

```
# Number of threads to use in the mapwriter plug-in
        threads = str(multiprocessing.cpu_count() - 1)
        if int(threads) < 1:
            threads = 1
```

Last line must be 
`threads = '1'`

**Comment by treee111** [comment]
Hi you two!
I looked deeper into it and found the mistake with your comments.
You are welcome to read and test #147 if this works for you.
Would be lovely if you could test it in your VM @zenziwerken, created a PyPI version for easy install :-)
