### ISSUE TITLE
Some POIs missing in created map

### ISSUE THREAD

**Issue by masc4ii** [treee111/wahooMapsCreator#144]
Hi, thank you for this great project!

## Expected Behavior
I created a map (tile 135/86, or entire germany) with tag-wahoo-poi.xml via command line on macOS and installed the map and the vtm-elemnt.xml with its icons on my Bolt v2. I would expect all supported pois to be shown on my device now.

## Current Behavior
All bakerys, some fuelstations and cafes are now shown on my device, while e.g. railway stations and halts are not shown at all. If I use the default map from wahoo, the bakeries, fuelstations and cafes are gone (to be expected), while railway halts are shown (but no station). If I use cruiser for the generated and for the default map, I get the same results.

## Steps to Reproduce the Issue
1. run `python -m wahoomc cli -xy 135/86 -tag tag-wahoo-poi.xml`
2. load map on wahoo or cruiser, load vtm-elemnt.xml with its icons too
3. see what you get

## Context
 * OS/Platform: macOS BigSur, Intel i7 MacBookPro
 * Used version: latest release 2.0.2, also develop branch
 * Other information regarding your environment *(optional)*: I already installed Python 3.18 via brew before, so I used this instead of anaconda. All other install steps were done as described in your docs.

**Comment by qiuchengxuan** [comment]
Maybe you could try specify `-fp` argument either?

**Comment by qiuchengxuan** [comment]
In file wahoomc/constants.py
Change TAGS_TO_KEEP_UNIVERSAL key `railway` like this:
```
'railway': ['abandoned', 'bus_guideway', 'disused', 'funicular', 'light_rail', 'miniature', 'narrow_gauge', 'preserved', 'rail', 'subway', 'tram', 'station', 'halt', 'stop'],
```
solves this problem

**Comment by masc4ii** [comment]
Yes, thank you, your answer is correct. I found out the same yesterday evening. For the problem, "half of existing POIs were shown only", I also found a solution:
some POIs are "node" and other POIs of the same type are "way" objects. In the tag xml node POIs are listed only. I forked and changed this plus some other things I like personally. Feel free to copy whatever you like!
https://github.com/masc4ii/wahooMapsCreator

**Comment by treee111** [comment]
Hi @masc4ii, thanks for your hints! I took over some of your adjustments with #158 ! :-)
Thanks for supporting the wahoo OSM community 👍

**Comment by utack** [comment]
Sorry to ask here, but where do I put the svg icons on my device?

**Comment by treee111** [comment]
Hi @utack,
it is described here: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/COPY_TO_WAHOO.md#copy-relevant-files-for-pois.

So the icons would be under `maps/vtm-elemnt/icons`. I.e. `maps/vtm-elemnt/icons/bakery.svg`.

That applies if you use the theme from this repo, because the path to the icon is defined in the theme. Example for bakery:
https://github.com/treee111/wahooMapsCreator/blob/26a7eaf19fb4821d096464584285c3bee22ac751/device_themes/vtm_theme_poi/vtm-elemnt.xml#L853

does that help?

**Comment by ghost** [comment]
Hi @treee111 ,

first of: some impressive work you're doing here regarding WahooMaps.

I just ordered a Elemnt Roam V2 and was already able to successfully change the VTM file and also added the POI's by copying your files.

But I noted today on a ride, that bakery's are not showing. Cafe do show up. So the POI-thing seems to work generally speaking.

Am I correct by assuming, that if a bakery is showing on OSM than it should be visible?

Thanks

BR
Erik
