### ISSUE TITLE
Processing canary islands results in empty tiles

### ISSUE THREAD

**Issue by masc4ii** [treee111/wahooMapsCreator#168]
## Expected Behavior
Processing a canary islands tile works.

## Current Behavior
Processing a canary islands tile brings an empty map of just some kb.

## Steps to Reproduce the Issue
call: 
`python -m wahoomc cli -xy 115/106`

## Context
 * OS/Platform: macOS

## My changes to make it work
Canary islands tiles aren't defined in spain - but they are in africa.
http://download.geofabrik.de/africa/canary-islands.html
f428c97a232a8a1ffd6c53cc61159cff84f7b1e3
2ad39b1e26a6f0587f8e9895faecad192a34dda6
84124e0c2993a7054af253789a6039ca3e0a08c0

**Comment by treee111** [comment]
thanks for finding & creating nice commits. I cherry-picked your commits 🔢
