### ISSUE TITLE
After uploading the map is black

### ISSUE THREAD

**Issue by nevuzer** [treee111/wahooMapsCreator#181]
Hi,
I have wahoo elemnt new roam.
I generated the map, put it into wahoo, added the contents of the devices_theme/vtm_theme_poi folder to vtm-elemnt. The map has loaded, I can see the POIs. But the map is almost whole black, which makes it unreadable.
I couldn't do the last step of the tutorial because adb doesn't detect my wahoo.

Is that why the map is black or did I do something else wrong?

Photo with my map: 
![IMG_20230218_205031](https://user-images.githubusercontent.com/101288324/219888643-580b7d87-7569-4fe1-8283-82ae02bb4242.jpg)

**Comment by nevuzer** [comment]
I managed to connect via adp, but executing the commands from the last point did not help. I also changed the stylemenu defaultvalue in the vtm-elemnt.xml file to BOLT, BOLT_V2, ROAM and the map went black every time.

Any idea what I am doing wrong? Or is it not working with the new ROAM?

**Comment by masc4ii** [comment]
I also got some minor trouble on Roam2, like randomly switching or combining sub themes. So I adapted the theme a little. Find it in my branch in my github.

**Comment by nevuzer** [comment]
@masc4ii I have another problem. I copied rendertheme.xsd from ./data/data/com.wahoofitness.bolt/files/apk_update/assets/maps/vtm-elemnt/vtm-elemnt.xml to vtm-elemnt. And right now I cant zoom my map. Instead of "..." I have "route".
![roam](https://user-images.githubusercontent.com/101288324/219941670-7f70c1af-46be-45ad-92eb-f09cf36b3204.jpg)

**Comment by nevuzer** [comment]
@masc4ii I tried to generate a map from your fork but I get this error

INFO:# Generate land for each coordinate
INFO:+ Generate land for each coordinate: OK
INFO:---------------------------------------------------------------------------
-----
INFO:# Generate sea for each coordinate
INFO:+ Generate sea for each coordinate: OK
INFO:---------------------------------------------------------------------------
-----
INFO:# Generate elevation for each coordinate
# Generate elevation 1 for coordinates: 144 82
Traceback (most recent call last):
  File "C:\Users\Death\anaconda3\envs\gdal-user\lib\runpy.py", line 193, in _run
_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Death\anaconda3\envs\gdal-user\lib\runpy.py", line 85, in _run_
code
    exec(code, run_globals)
  File "C:\Users\Death\ana\masc4ii\wahooMapsCreator\wahoomc\__main__.py", line 7
, in <module>
    main.run("run")
  File "C:\Users\Death\ana\masc4ii\wahooMapsCreator\wahoomc\main.py", line 77, i
n run
    o_osm_maps.generate_elevation()
  File "C:\Users\Death\ana\masc4ii\wahooMapsCreator\wahoomc\osm_maps_functions.p
y", line 553, in generate_elevation
    result = subprocess.run(cmd)
  File "C:\Users\Death\anaconda3\envs\gdal-user\lib\subprocess.py", line 488, in
 run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Death\anaconda3\envs\gdal-user\lib\subprocess.py", line 800, in
 __init__
    restore_signals, start_new_session)
  File "C:\Users\Death\anaconda3\envs\gdal-user\lib\subprocess.py", line 1207, i
n _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku

**Comment by masc4ii** [comment]
You already had maps I think, and just a problem with themes?! So try the themes, not the maps from my branch. With anaconda I can't help at all. I use brew and python3 on macOS. And you need an account on US government for elevation data to use the latest code on my repos. Adapt the lines in elevation code (user & password), if you want to build maps with it. Or use one commit later (older).

```
cmd.extend(['-o', f'{outFile}', '-s 10', '-c 100,50', '--source=view1,view3,srtm3',
                            '--jobs=8', '--viewfinder-mask=1', '--start-node-id=20000000000', 
                            '--max-nodes-per-tile=0', '--start-way-id=2000000000', '--write-timestamp', 
                            '--no-zero-contour', '--earthexplorer-user=<yourUserName>', '--earthexplorer-password=<yourPassword>'])
```

**Comment by nevuzer** [comment]
@masc4ii great job!!
The map looks much better but I still preferred the look of the original map from roam 2. Is there a theme that looks like the original map and has POIs?

![abb](https://user-images.githubusercontent.com/101288324/219950438-a7df0301-66c3-47b5-aea5-45025caea4b9.jpg)

**Comment by masc4ii** [comment]
I don't know any. You just could write your own theme then. The rules aren't difficult to learn. There are some other themes, but they all look very different, compared to stock theme.

**Comment by treee111** [comment]
Hi @nevuzer,
thanks for opening this issue and using the tool! Nice, that you found you way here :-)
The theme in my repo isn't the most recent one, there are other people knowing better about themes.
@masc4ii and you figuered out everything already - perfect!

Here are also some more themes you can try: https://my.hidrive.com/share/1t65k1b0lb#$/Windows-Wahoo-Map-Creator-Osmosis-v2-Maps/Sample%20Themes
Get the one suits you most and adapt to your preferences. You'll find help in the telegram group mentioned in README.md

**Comment by nevuzer** [comment]
@treee111, @masc4ii thanks for your work, it is amazing.
I extracted the original vtm-elemnt.xml file from wahoo and added POIs to it. Looks like the original map with POIs added. I need to add more POIs that I need.

Btw. don't know why wahoo doesn't add these POIs to the map. They are very useful.

**Comment by masc4ii** [comment]
Sry... that is interesting for me too: there is an original wahoo theme? Where to find this?

**Comment by nevuzer** [comment]
You can download vtm-elemnt from your wahoo with the command:
`adb pull /data/data/com.wahoofitness.bolt/files/apk_update/assets/maps/vtm-elemnt .`

**Comment by masc4ii** [comment]
Thank you! Great!

**Comment by Ebe66** [comment]
Or download the firmware on your computer, rename the file to .zip and extract it.
In the theme you can see they "ignore" the bolt and roam 1. 
@treee111 I already tried to tell you a few times, but that is why Zenziwerken's theme does in all likelihood will not work correctly anymore with all devices except bolt2 and "by accident" roam2

**Comment by Ebe66** [comment]
@treee111 the resulting map being all black is a result of the -poi theme here defaulting to the bolt 1
`<stylemenu id="stylemenu" defaultvalue="BOLT" defaultlang="en">`
So unless you have a bolt_2 you will end up with the bolt 1 rulesets.
Maybe set the default to bolt_2? Even if the device used does not match it will show better results than this.

**Comment by treee111** [comment]
> @treee111 I already tried to tell you a few times, but that is why Zenziwerken's theme does in all likelihood will not work correctly anymore with all devices except bolt2 and "by accident" roam2
i know you told me. Had no time until now to look into this.

> @treee111 the resulting map being all black is a result of the -poi theme here defaulting to the bolt 1 `<stylemenu id="stylemenu" defaultvalue="BOLT" defaultlang="en">` So unless you have a bolt_2 you will end up with the bolt 1 rulesets. Maybe set the default to bolt_2? Even if the device used does not match it will show better results than this.

done with https://github.com/treee111/wahooMapsCreator/commit/16a1586e4328c35f4c8fd46c095a06643d302e1e, could you please have a look is that is correct. Thanks!
