### ISSUE TITLE
Wahoo does not show next turn

### ISSUE THREAD

**Issue by nevuzer** [treee111/wahooMapsCreator#185]
Hi,
I have another problem. I generated a map and uploaded it to wahoo. Unfortunately when navigating it does not show the next turn. On the original map the turns are shown.

**Comment by nevuzer** [comment]
I did it. I just updated the map in wahoo and the map i soriginal from wahoo with POIs added.
If I reinstall the map from scratch and add the vtm-elemnt folder with icons and configuration file then there are no POIs.

**Comment by treee111** [comment]
Hi @nevuzer, sorry for the late reply. Are your issues still happening?

> Unfortunately when navigating it does not show the next turn. On the original map the turns are shown.

How do you navigate? When navigation using a planned route from komoot etc. the routing is taken from there. So the generated maps should not interfere.
When routing via e.g. ROAM2 on-device functionality, routing tiles should be updated in addition to the generated maps.

> I did it. I just updated the map in wahoo and the map i soriginal from wahoo with POIs added. If I reinstall the map from scratch and add the vtm-elemnt folder with icons and configuration file then there are no POIs.

Could you please elaborate a little more:
- Which maps do you have on the device now?
- which device do you use?
- which theme do you use?

Thanks!

**Comment by VladimirPomogaev** [comment]
> When routing via e.g. ROAM2 on-device functionality, routing tiles should be updated in addition to the generated maps.
> 
> >

Hi @treee111 ! And thank you for your project! 
And how can I update routing tiles?

**Comment by treee111** [comment]
Hi @VladimirPomogaev, thanks :-)
I documented it here: https://github.com/treee111/wahooMapsCreator/blob/routing-tiles/docs/FAQ.md#does-offline-routing-functionality-use-the-new-roads

**Comment by VladimirPomogaev** [comment]
@treee111 thanks a lot for the answer! 
Unfortunately, there is no such data for Russia. I understand that this is not really on the topic, but is it possible to generate this data yourself?

**Comment by treee111** [comment]
It is described here: https://github.com/treee111/wahooMapsCreator/issues/189#issuecomment-1486650482
If you need further assistance or want to ask for someone create that for you, please reach out in the telegram group - see README. As this is really offtopic here, I will close the issue now.
