### ISSUE TITLE
Contour lines was not display

### ISSUE THREAD

**Issue by mushroom11s** [treee111/wahooMapsCreator#211]
System version: 15944
Device:Roam V2
device_themes: /[device_themes](https://github.com/treee111/wahooMapsCreator/tree/develop/device_themes/vtm_theme_poi/
Img:
![38c55e54f26b3fc20371078a595e5c4d](https://github.com/treee111/wahooMapsCreator/assets/28756933/cab745cb-a856-433d-9610-4ddfaceff596)

Contour lines was not display.Is it because the themes of Roam are not compatible V2？

**Comment by treee111** [comment]
Hi @mushroom11s!
the device theme in my repo is universal but tailored for BOLTv1. There might be not enough configured to display contour lines on a ROAMv2.

You might read here and try the theme from @masc4ii, this is tailored for BOLTv2 and contour lines :-)
Just to make sure: did you generate maps including contour lines? This is a prerequesite.

**Comment by mushroom11s** [comment]
> Hi @mushroom11s! the device theme in my repo is universal but tailored for BOLTv1. There might be not enough configured to display contour lines on a ROAMv2.
> 
> You might read here and try the theme from @masc4ii, this is tailored for BOLTv2 and contour lines :-) Just to make sure: did you generate maps including contour lines? This is a prerequesite.

Yes. I have included Contour line on the map. The generation time is too long!!! 😭😭
I am generating a map for China, and this basic data is too large (approximately 450G). I spent 2 days generating it.

**Comment by treee111** [comment]
:-D Wow! Yes contour lines take some additional times. What you could do actually is to only generate certain XY-coordinates. That's what I sometimes do (before holiday etc.) to have new maps for a specific region.

Sorry I forgot to link to the theme I mentioned, here it is:
https://github.com/treee111/wahooDeviceThemes/tree/link-themes/VTM/masc4ii

**Comment by mushroom11s** [comment]
Thank！May be can provide the provincial level generation. 
I'm sorry, I don't have much knowledge of GIS and can't provide some help in implementing this feature.
I can only wait for you to do it well.🙏🏻😐

**Comment by treee111** [comment]
Have you been able to display contour lines with the theme I mentioned?

Think of implementing a provincial possibility, that might not be doable on a geofabrik way for China:
- http://download.geofabrik.de/asia/china.html has no subregions
- http://download.geofabrik.de/europe/germany.html in comparison has subregions

**Comment by mushroom11s** [comment]
> Have you been able to display contour lines with the theme I mentioned?
> 
> Think of implementing a provincial possibility, that might not be doable on a geofabrik way for China:
> 
> * http://download.geofabrik.de/asia/china.html has no subregions
> * http://download.geofabrik.de/europe/germany.html in comparison has subregions

🙏🏻😸
Yes,is worked. But contour line value is not displayed on line.I don't know how to configure it.
![image](https://github.com/treee111/wahooMapsCreator/assets/28756933/5b564312-abd4-4b68-bee1-4d1354557b62)

If I want use the command line to generate some areas like img.What "- xy" value do I need to enter?
<img width="1727" alt="image" src="https://github.com/treee111/wahooMapsCreator/assets/28756933/eed9ecb3-4ad1-49b6-9d55-23fd17de2c04">

**Comment by treee111** [comment]
perfect that contour lines are displayed! I don't think the height meters are included in the map and thus it's not possible to display them. Would clutter the display also too much maybe

`-xy` is documented [here](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/USAGE.md#main-arguments). Just follow the link given there and zoom into your area with zoom level = 8 `z=0`
You can also supply more that one xy-coordinate to the tool (i.e. your area!)

should be that, right?
![grafik](https://github.com/treee111/wahooMapsCreator/assets/53038537/113d6b60-fc08-4be5-be03-1cfd297408e4)

**Comment by mushroom11s** [comment]
> Just follow the link given there and zoom into your area with zoom level = 8 `z=0`
> You can also supply more that one xy-coordinate to the tool (i.e. your area!)

Thanks very much! This answer is very helpful. Thank you for your patient response.
I immediately understood when I saw this picture,I used to think that xy was just a point, not an area😅

**Comment by treee111** [comment]
> I immediately understood when I saw this picture,I used to think that xy was just a point, not an area😅

you are welcome! Maybe I should add a little more information about xy in the docs 👍
