### ISSUE TITLE
ADB commands for Roam

### ISSUE THREAD

**Issue by JackCaster** [treee111/wahooMapsCreator#213]
I think that the ADB commands in the docs [COPY_TO_WAHOO.md](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/COPY_TO_WAHOO.md#delete-temp-files-and-clear-cache) to purge and reload the maps on the Bolt are exactly the same as for the Roam. 

I tried the following on my Roam and the maps were reloaded
```
adb shell am broadcast -a com.wahoofitness.bolt.service.BMapManager.PURGE
adb shell am broadcast -a com.wahoofitness.bolt.service.BMapManager.RELOAD_MAP
```
while, my previous attempt to use `roam` instead of `bolt` did not yield anything

**Comment by treee111** [comment]
Hi @JackCaster,
thanks for the hint, the documentation lacks at this point! It is the same for all devices. 
Have corrected it via https://github.com/treee111/wahooMapsCreator/commit/fa3b39983f516d16ed51833349a3ad4b68da6dff.

It this understandable now or do you have a better wording?
Thanks!

**Comment by JackCaster** [comment]
looks good!
