### ISSUE TITLE
Streetnames

### ISSUE THREAD

**Issue by ghost** [treee111/wahooMapsCreator#215]
## Is your feature request related to a problem? Please describe.
When exporting maps, i can't see any streetnames in the device - is there any way to include them?

**Comment by h0nkX** [comment]
Ebe66 allready helped me out on this in the rennradforum.

**Comment by ghost** [comment]
Ebe66 allready helped me out on this in the rennradforum.
`To leave the street names in the map you just have to move the highway section in the json file to the NAME_TAGS_TO_KEEP_UNIVERSAL section`

**Comment by treee111** [comment]
nice that you found your way - @Ebe66 knows more or less everything in this area ;-)
