### ISSUE TITLE
Routing tiles 

### ISSUE THREAD

**Issue by ldimlight** [treee111/wahooMapsCreator#218]
Any plans on generating routing tiles (*.gph) alongside map tiles?

**Comment by VladimirPomogaev** [comment]
I join the question

**Comment by treee111** [comment]
Hi you two!
Sorry for the late reply. I have no plans on generating routing tiles with wahooMapsCreator at the moment.
Please find in the [FAQ](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/FAQ.md#does-deviceoffline-routing-functionality-use-the-new-roads) where to get already generated routing tiles.

There is also a basic documentation in this [repo](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/HOWTO_ADD_ROUTING_TILES_MANUALLY.MD#how-to-add-routing-tiles-manually-for-wahoo-elemnt-roam) but I don't know it this works, I have never generated routing tiles (and also have no device supporting offline routing).
In the [telegram group](https://github.com/treee111/wahooMapsCreator/tree/develop#contribution--questions) are some specialists which have been successful in generating routing tiles. Feel free to ask them and work towards a shareable solution for generating routing tiles :-)

**Comment by quietvoid** [comment]
> There is also a basic documentation in this [repo](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/HOWTO_ADD_ROUTING_TILES_MANUALLY.MD#how-to-add-routing-tiles-manually-for-wahoo-elemnt-roam) but I don't know it this works, I have never generated routing tiles (and also have no device supporting offline routing).

Though the instructions aren't clear I've had success with scripting the tiles downloading: https://gist.github.com/quietvoid/5713950bf978c6bc955097c7aa6d6724
Can't confirm if it's proper but it seemed to work.

Maybe this is useful for OP.
