### ISSUE TITLE
Areas with landuse=farmland cover some tracks with vtm_theme_poi

### ISSUE THREAD

**Issue by the-kenny** [treee111/wahooMapsCreator#221]
## Expected Behavior

The VTM-POI theme seems to have an issue with some `highway=track`s enclosed in `landuse=farmland`.

This is a screenshot around [Pulheim, Germany on openstreetmap.org](https://www.openstreetmap.org/search?whereami=1&query=50.9800%2C6.8093#map=14/50.9800/6.8093&layers=D):

<img width="520" alt="Screenshot 2023-10-30 at 09 42 30" src="https://github.com/treee111/wahooMapsCreator/assets/31167/dabe32e1-404d-4a3b-b115-bd4f848a2574">

## Current Behavior

This is the same screenshot on my Bolt V2 using `vtm_theme_poi`.

![download](https://github.com/treee111/wahooMapsCreator/assets/31167/f51c4fc2-5f2d-4826-833e-557f9b3e01ef)

Notice the missing tracks and the disappearance of `23086785` (`tracktype=grade1`, upper right, left of the 'B59' label) when it changes into `589774107` (`tracktype=grade2`). It seems like everything 'lower' than `grade1` is rendered either behind a white overlay of `landuse=farmland` or with the same color as the background (you can notice this on higher zoom levels on the Bolt - the rounded edges of the tracks sometimes 'leak' into other, visible tracks).

## Context
 * OS/Platform: `Bolt v2 (BOLT WA49-16335)`
 * Rendered on `2023-10-28` on `macOS 14 (23A344)` using wahooMapsCreator [cedcd30](https://github.com/treee111/wahooMapsCreator/commit/cedcd300f25b40bce3cd7edc32e0169061b5b9cf)

Unfortunately I'm not experienced in modifying VTM themes and can only guess the issue. I'm happy to tackle this myself if you can give me a rough guidance on what I need to do.

## Log Output / Stack Trace

```
{...}
```

**Comment by alfh** [comment]
@the-kenny Can you confirm that this is the tile 132/85 , using https://tools.geofabrik.de/map/#8/50.0969/8.2753&type=Geofabrik_Standard&grid=1 ?

**Comment by alfh** [comment]
![cruiser_vtm_render_issue_221](https://github.com/treee111/wahooMapsCreator/assets/1822222/6dabca31-410a-439d-b732-7332d05ff197)

This is how the area (I think), looks in cruiser, using the device_themes/vtm_theme_poi theme.
As far as I can see, it is not even rendered there at all ?

Are the 23086785 and 589774107 you mention, OpenStreetMap object ids ?
So https://www.openstreetmap.org/api/0.6/way/589774107 and
https://www.openstreetmap.org/way/589774107, https://www.openstreetmap.org/way/23086785 ?

**Comment by the-kenny** [comment]
Hey @alfh!

It's tile 132/85, more specifically [this](https://tools.geofabrik.de/map/#15/50.9832/6.8035&type=Geofabrik_Standard&grid=1&mlat=50.98392&mlon=6.80648) area. The mentioned IDs are in fact OSM-ids and the links you provided link to the correct ways. 

Your screenshot is showing the affected area correctly, including the paths that don't show up on my Bolt v2. The black dashed horizontal line on your screenshot is [this path](https://www.openstreetmap.org/way/589774107) should be visible right below the 'B 59' label on my bolt-screenshot. The other paths in your screenshot should be visible too. 

I had another thought of a possible cause of this issue on a recent ride: Could it be that the paths are simply rendered with the same color as the background on-device?

**Comment by alfh** [comment]
@the-kenny Exactly what theme xml are you using ?

I noticed that there are differences on what zoom level the "grade1" and "grade2" are shown on, it appears.
It can also be a colour problem, I have not looked into that yet.

From https://github.com/treee111/wahooMapsCreator/blob/develop/device_themes/vtm_theme_poi/vtm-elemnt.xml
```
         <m e="way" k="highway" v="track|byway" zoom-min="13" select="first">
            <m k="tracktype" v="grade1">
               <!-- Solid. Usually a paved or sealed surface-->
               <m k="bicycle" v="bic_yes|bic_designated">
                  <line use="bolt-track-paved-cycle" dasharray="10,7"/>
                  <line use="roam-track-paved-cycle" dasharray="10,7"/>
                  <line use="bolt2-track-paved-cycle" dasharray="10,7"/>
               </m>
               <m k="bicycle" v="~">
                  <line use="bolt-track-paved" dasharray="10,7"/>
                  <line use="roam-track-paved" dasharray="10,7"/>
                  <line use="bolt2-track-paved" dasharray="10,7"/>
               </m>
            </m>
            <m zoom-min="14">
               <m k="tracktype" v="grade2">
                  <!-- Solid but unpaved. Usually an unpaved track with surface of gravel. -->
                  <m k="bicycle" v="bic_yes|bic_designated">
                     <line use="bolt-track-raw-cycle" dasharray="10,7" />
                     <line use="roam-track-raw-cycle" dasharray="10,7" />
                     <line use="bolt2-track-raw-cycle" dasharray="10,7" />
                  </m>
                  <m k="bicycle" v="~">
                     <line use="bolt-track-raw" dasharray="10,7" />
                     <line use="roam-track-raw" dasharray="10,7" />
                     <line use="bolt2-track-raw" dasharray="10,7" />
                  </m>
               </m>
```

From
https://github.com/zenziwerken/Bolt2-Mapsforge-VTM-Rendertheme/blob/main/vtm-elemnt.xml
```

				<m e="way" k="highway" v="track|byway|path" zoom-min="12" zoom-max="12">
					<m k="tracktype" v="grade1">
						<line cat="roam" stroke="#000000" width="2" cap="round"/>
						<line cat="bolt2" stroke="#AAAAAA" width="2" cap="round"/>
					</m>
				</m>
				<m e="way" k="highway" v="track|byway" zoom-min="13" select="first">
					<m k="bicycle" v="bic_yes|bic_designated">
						<!-- specifically for cycle -->
						<m k="surface" v="bic_paved">
							<line use="roam-trail" outline="roam-bikepath"/>
							<line use="bolt2-trail" outline="bolt2-bikepath"/>
						</m>
					</m>
					<m k="tracktype" v="grade1">
						<!-- Solid. Usually a paved or sealed surface-->
						<m k="bicycle" v="bic_yes|bic_designated">
							<line use="roam-track-paved-cycle"/>
							<line use="bolt2-track-paved-cycle"/>
						</m>
						<m k="bicycle" v="~">
							<line use="roam-track-paved"/>
							<line use="bolt2-track-paved"/>
						</m>
					</m>
					<m k="tracktype" v="grade2|grade3" zoom-min="12" zoom-max="13">
						<line cat="roam" stroke="#000000" width="1.2" dasharray="15,5" cap="round"/>
						<line cat="bolt2" stroke="#AAAAAA" width="1.2" dasharray="15,5" cap="round"/>
					</m>
					<m zoom-min="14">
						<m k="tracktype" v="grade2">
							<!-- Solid but unpaved. Usually an unpaved track with surface of gravel. -->
							<m k="bicycle" v="bic_yes|bic_designated">
								<line use="roam-track-raw-cycle" dasharray="50,3,5,3,5,3"/>
								<line use="bolt2-track-raw-cycle" dasharray="50,3,5,3,5,3"/>
							</m>
							<m k="bicycle" v="~">
								<line use="roam-track-raw" dasharray="50,3,5,3,5,3"/>
								<line use="bolt2-track-raw" dasharray="50,3,5,3,5,3"/>
							</m>
						</m>
```

**Comment by the-kenny** [comment]
@alfh I'm using [`device_themes/vtm_theme_poi/vtm-elemnt.xml`](https://github.com/treee111/wahooMapsCreator/blob/develop/device_themes/vtm_theme_poi/vtm-elemnt.xml). I don't have the device on me to verify right now, but I'm 95% sure the paths aren't visible on any zoom level the Bolt2 supports.

**Comment by Ebe66** [comment]
@the-kenny @treee111 @alfh 

Pretty old issue, but I think I know the reason. 
Line 85 of the poi theme uses a color that is invalid for the v2 Wahoo devices:
`<style-line id="bolt2-track-raw-cycle" cat="bolt2" stroke="#CCCCCC" dasharray="6,3"/>`
Change the #CCCCCC (invalid) to #000000 and these tracks should be visible as black dashed lines.

The #CCCCCC works on Cruiser and shows as a light grey

**Comment by the-kenny** [comment]
@Ebe66 I'll try this in a minute and create a PR if it works. Thanks!

**Comment by the-kenny** [comment]
I can confirm the fix is working. Thanks!

![image](https://github.com/treee111/wahooMapsCreator/assets/31167/f52a57b7-5833-48e2-bfb0-7888da14396e)

**Comment by Ebe66** [comment]
Thanks for the feedback @the-kenny and great to hear it works!
