### ISSUE TITLE
Support of veloviever tile oververlay

### ISSUE THREAD

**Issue by samur2** [treee111/wahooMapsCreator#238]
## Is your feature request related to a problem? Please describe.
A clear and concise description of the problem, e.g. "I'm always frustrated when {...}"

## Describe the solution you'd like
Hello. How difficult do you think it would be to include a veloviewer tile overlay in these maps? The idea being that while out riding, you would be able to see which tiles you haven't visited, or could use it to ensure you have visited a tile. Veloviewer exports it's tile maps in KML format. There are online guides for converting into OSM for Garmin devices but this is the only thing I have found for Wahoo's. Thanks. Jon.

**Comment by treee111** [comment]
Hi @samur2, i think we have done something similar in #179.
Maybe this gives a hint. Other than that I am happy for PR's concerning this topic but can not look into this myself because I dont use veloviewer at the moment.
