### ISSUE TITLE
Question about adding POIs to original wahoo map

### ISSUE THREAD

**Issue by nevuzer** [treee111/wahooMapsCreator#239]
Hello,
Is there a way to take the original wahoo map and add POIs to it?

**Comment by treee111** [comment]
Hi @nevuzer, as of now this is not possible. the original maps are "generated" ones and the "last" format of the map-processing process. You would most probably need to bring the original maps in a "editable" format as we have them in a prestep of the map-processing process. As said, not supported actually.
