### ISSUE TITLE
Add information create routing automatically

### ISSUE THREAD

**Issue by lockevod** [treee111/wahooMapsCreator#240]
Hello! Great job. I'm trying to generate routing automatically and I suppose you're using mjolnir but if you can provide some info, it'll be very appreciate (in your onedrive, i can see you generate routing files directly)

Thanks

**Comment by treee111** [comment]
Hi, thanks, was a lot of work, nice that many people find the tool helpful!

It is not my onedrive and I also have not generated not uploaded the routing files there. They are generated and uploaded by Ebe66.

Here some links that might bring you further:
- FAQ in my repo to the routing tiles: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/FAQ.md#does-deviceoffline-routing-functionality-use-the-new-roads
- in my knowledge, valhalla is used to generate routing tiles, an (old) documentation is also in my repo: https://github.com/treee111/wahooMapsCreator/blob/develop/docs/HOWTO_ADD_ROUTING_TILES_MANUALLY.MD
- version of wahoomapscreator to generate the map files: https://github.com/Ebe66/Windows-Wahoo-Map-Creator-Osmosis, there is also a "valhalla config" file

You can also go to the telegram group mentioned in the README.md, there are guys knowing more about routing tiles.
As I don't have a device capable of routing offline, I will not dig into this topic as of now.

Hope that helps!
