### ISSUE TITLE
Question: Can't Find POI Files

### ISSUE THREAD

**Issue by simonf00** [treee111/wahooMapsCreator#241]
Hello,

Thank you for all your work on this project!! 

I ran the tool successfully on my Mac (Intel). After several days (!!) the maps generation finished, but I'm unable to find the POI files [mentioned in your documentation](https://github.com/treee111/wahooMapsCreator/blob/develop/docs/COPY_TO_WAHOO.md#copy-relevant-files-for-pois). The "device_themes/vtm_theme_poi" does not appear in the output directory. Am I missing a command-line argument or simply not noticing the files?

Thanks again for your great project.

**Comment by Ebe66** [comment]
Hi,

Maybe you figured it out already, but the POI files are not created by the mapscreator so they are not located in the output directory. The files mentioned in your documentation link are here on the github page: https://github.com/treee111/wahooMapsCreator/tree/develop/device_themes/vtm_theme_poi

**Comment by simonf00** [comment]
Sorry, I'm not following what you're saying. I still can't seem to find any device_themes/vtm_theme_poi directory anywhere.

**Comment by Ebe66** [comment]
Just click on the link I provided in my previous post it will take you there.
The files are part of this repository.  Click "code" on the top left on this page, than device_themes and finally vtm_theme_poi and you are there.

![Screenshot 2024-04-15 213143](https://github.com/treee111/wahooMapsCreator/assets/88671974/9788e440-e85e-4028-9681-e0fa197bd7b2)

**Comment by treee111** [comment]
thanks for helping out @Ebe66, closing this issue as resolved. If there are still questions to the same topic, please reopen.
