### ISSUE TITLE
Tiles were not generated but wahoomc logs said they were 

### ISSUE THREAD

**Issue by lacovajuan** [treee111/wahooMapsCreator#244]
## Expected Behavior
after running 
python -m wahoomc cli -xy 251,199

I expected to find the tile 251,199 at ~/wahooMapsCreatorData/_tiles
## Current Behavior
however the _tiles folder was empty

## Steps to Reproduce the Issue
run
python -m wahoomc cli -xy 251,199

## Context
 * OS/Platform: ubuntu 22.04
 

## Log Output / Stack Trace
INFO:Last run was with version None, deleting files of /home/juanelvira/wahooMapsCreatorData/_tiles directory due to breaking changes.
INFO:Last run was with version None, deleting files of /home/juanelvira/wahooMapsCreatorData/_download/maps directory due to breaking changes.
INFO:Last run was with version None, deleting files of /home/juanelvira/wahooMapsCreatorData/_tiles directory due to breaking changes.
INFO:# Need to download geofabrik file
INFO:--------------------------------------------------------------------------------
INFO:# Downloading geofabrik.json file
INFO:+ Downloaded: /home/juanelvira/wahooMapsCreatorData/_download/geofabrik.json
INFO:--------------------------------------------------------------------------------
INFO:--------------------------------------------------------------------------------
INFO:# check geofabrik.json file
INFO:# Input X/Y coordinates: 251,199.
INFO:--------------------------------------------------------------------------------
INFO:# Determine involved/border countries
INFO:+ Border countries will be processed
INFO:--------------------------------------------------------------------------------
INFO:# check land_polygons.shp file
INFO:+ land_polygons.shp file needs to be downloaded
INFO:+ Need to download land polygons file
INFO:--------------------------------------------------------------------------------
INFO:# check countries .osm.pbf files
INFO:+ Checking for old maps and remove them
INFO:--------------------------------------------------------------------------------
INFO:# Downloading land_polygons.shp file
INFO:+ Downloaded: /home/juanelvira/wahooMapsCreatorData/_download/land-polygons-split-4326/land_polygons.shp
INFO:--------------------------------------------------------------------------------
INFO:# Filter tags from country osm.pbf files
INFO:+ Filter tags from country osm.pbf files: OK
INFO:--------------------------------------------------------------------------------
INFO:# Generate land for each coordinate
INFO:+ Generate land for each coordinate: OK
INFO:--------------------------------------------------------------------------------
INFO:# Generate sea for each coordinate
INFO:+ Generate sea for each coordinate: OK
INFO:--------------------------------------------------------------------------------
INFO:# Split filtered country files to tiles
INFO:+ Split filtered country files to tiles: OK
INFO:--------------------------------------------------------------------------------
INFO:# Merge splitted tiles with land, elevation and sea
INFO:+ Merge splitted tiles with land, elevation and sea: OK
INFO:--------------------------------------------------------------------------------
INFO:# Creating .map files for tiles
INFO:+ Creating .map files for tiles: OK
INFO:--------------------------------------------------------------------------------
INFO:# Create: .map.lzma files
INFO:+ Country: 
INFO:+ Copying .map.lzma tiles to output folders
INFO:+ Create .map.lzma files: OK

**Comment by Ebe66** [comment]
@lacovajuan 
Strange to see all the "OK" messages without generating the actual files, but as a way to reproduce you say:
python -m wahoomc cli -xy 251,199
According to the documentation this should be:
python -m wahoomc cli -xy 251/199
But I guess you did that as the program seems to recognize the coordinates in the log.

I do not use this version of wahoomc so I can't say where temporary files are stored, but you might want to try to see if anything is actually created there at all while the program is running. Look for filenames with split-{country}.osm.pbf for example where (country) would be the name of the country needed for the tile. Or land1.osm.
I think that these temp files are deleted at the end of the program so really look during the execution of wahoomc.

Considering the tile you try to create, it might be better to try a coordinate that actually includes land? 251/199 is a piece of ocean of the coast of the antarctic?
Use this url to find a tile (with land) to create [https://tools.geofabrik.de/map/?type=Geofabrik_Standard&grid=1&mlat=-70.47159&mlon=173.44709#8/50.7072/10.1793](https://tools.geofabrik.de/map/?type=Geofabrik_Standard&grid=1&mlat=-70.47159&mlon=173.44709#8/50.7072/10.1793) You have to stay on zoom level 8 to find the right coordinates.
Try 138/100 for Malta from your other post.

**Comment by treee111** [comment]
Hi @lacovajuan, thanks for your issue.

I am with @Ebe66, I think the tile you try to create has no land in it, this can also be seen in you log, no countries are downloaded.

We could try to check the temporary folders for files but I doubt creating maps for this tile would make sense.
I'm closing this issue. Please open again or create a separate one if creating a file for the tile I post or country malta does not work. Thanks!

For reference the output of `python -m wahoomc cli -xy 134/89 `. See the listed contries in the second log-block.
```
INFO:--------------------------------------------------------------------------------
INFO:--------------------------------------------------------------------------------
INFO:# check geofabrik.json file
INFO:# Input X/Y coordinates: 134/89.
INFO:+ Searching for needed maps, this can take a while.
INFO:--------------------------------------------------------------------------------
INFO:# Determine involved/border countries
INFO:+ Involved country: austria
INFO:+ Involved country: germany
INFO:+ Involved country: liechtenstein
INFO:+ Involved country: switzerland
INFO:+ Border countries will be processed
INFO:--------------------------------------------------------------------------------
INFO:# check land_polygons.shp file
INFO:--------------------------------------------------------------------------------
INFO:# check countries .osm.pbf files
INFO:+ Checking for old maps and remove them
INFO:+ mapfile for austria: deleted.
INFO:+ mapfile for germany: deleted.
INFO:+ mapfile for liechtenstein: deleted.
INFO:+ mapfile for switzerland: deleted.
INFO:--------------------------------------------------------------------------------
INFO:# Downloading austria-latest.osm.pbf file
```
