### ISSUE TITLE
Cruiser not working with default VTM theme

### ISSUE THREAD

**Issue by Roryplewes** [treee111/wahooMapsCreator#245]
## Expected Behavior
When using cruiser we upload the map we want to view, then select the wahoo theme we wish to see the map viewed as from the theme repository from github.

## Current Behavior
We in cruiser and selecting the VTM theme I get an error of "Unknown element: style-line"

## Steps to Reproduce the Issue
1. Download most recent version of cruiser.
2. Download anymap in .map format
3. Download vtm-elemnt.xml file from the theme repository
4. Open cruiser and import map
5. Select open map theme and select the downloaded vtm-elemnt.xml file.
6. Error message should appear

## Context
 * OS/Platform: `Mac`
 
 For boltV2

**Comment by masc4ii** [comment]
Cruiser VTM doesn't work on 64bit macOS by default, as the VTM libraries are 32bit only at the moment! That is a known issue of cruiser - see issues on this side (vtm library used by cruiser). This is no issue of the code in this repo.

You can get it working using 32bit Wine starting the Windows bat file. Or use an old macOS having native 32bit support.

**Comment by Roryplewes** [comment]
Sorry, not the most computer savvy but have managed to get custom maps to work.I have managed to get it to all work on my wahoo but not fully satisfied with how certain trails are shown on the map so using cruiser will be essential to testing this. 

so what your saying is if I run cruiser on a windows pc I will be fine. Or use an old mac, how would I see if its 32 bit?

**Comment by Ebe66** [comment]
I can't comment on anything MacOS related being on Windows. 
But I might be able to say something about Cruiser. Cruiser's default rendering engine is MapsForge and when you try to load a vtm render theme while set to MApsForge you get this message because it's not a valid MapsForge render instruction.
In Cruiser go to settings on the top right then Rendering engine and select VTM. This will 100% work on windows

**Comment by Roryplewes** [comment]
When I am on cruiser I dont have a rendering engine setting?

**Comment by Ebe66** [comment]
Doubt it's different on macos but see screenshot for the windows version:
![image](https://github.com/treee111/wahooMapsCreator/assets/88671974/e3668446-fc39-4dbe-83f4-637a0fd11c2b)

**Comment by masc4ii** [comment]
You can't get the VTM render engine on 64bit macOS. You can try by changing the call in the .sh file, but then you get other errors. When did macOS go 64bit: not exactly sure, was it Catalina? On 10.13 it works fine here. On newer macOS you just can try the Wine workaround.

**Comment by treee111** [comment]
Thanks for helping out @masc4ii and @Ebe66!

This is a related discussion about using cruiser on macOS: https://github.com/mapsforge/vtm/issues/1004#issuecomment-1993790604 and https://github.com/devemux86/cruiser/discussions/20#discussioncomment-8764714
