### ISSUE TITLE
Map Source Data

### ISSUE THREAD

**Issue by Roryplewes** [treee111/wahooMapsCreator#247]
Hopefully an easy question to answer.

Where does the map get generated from. I assumed open street map but when selecting 0 or 1 days old I cant see paths that have recently been added on the map (Or their changed route), also changed to surfaces or path types or access.

So I wondered if it uses the most up to date OSM data or how long I need to wait to get a days map.
For example if I wanted how OSM looked today (9th June 2024) I need to run the download from the terminal on the 16th June 2024 and then it would show all the updates?

**Comment by Ebe66** [comment]
Hi,

The source is Openstreetmap, but the files are downloaded from Geofabrik. 
This is one of the parties that provides file download of the Openstreetmap data. That data is not updated the moment a way is added to Openstreetmap. There is a sync interval but I do not know what it is. Geofabrik provides region downloads, see [https://download.geofabrik.de](url) If I look at my country, the Netherlands, there is a " status" line near the top stating "This file was last modified 13 hours ago and contains all OSM data up to 2024-06-08T20:21:12Z. " So there you can see how "old" the data is that is used by the WahooMapsCreator.
Geofabrik also provides change files, those contain the most up to date information and can be used to optionally bring your map file to the newest state possible. Those files appear to be created hourly. 
I do update my map files using these change files from within wsl/ubuntu with "pyosmium-up-to-date -v -v -v --force-update-of-old-planet netherlands-latest.osm.pbf" for example.

**Comment by Roryplewes** [comment]
Thanks so much for that information that is really useful. 
Unfortunatelt I am not able to bring my ma file to the newest version as there isnt something that explains it well enough. However as I am only doing the UK it only takes about 30-60 minutes to download anyway.

I assume by the way you have said it that only the most map file information is downloaded? In other words the last modified version is downloaded?

**Comment by Ebe66** [comment]
Wow, that's a slow download ;-) 
But yes, only the latest complete map file is downloaded, not including the change files. So the status line on the website tells you the age of the file you are going to get with WahooMapsCreator.,
It is not normally needed to use the change files, but if you are up for it I could try to get you there. (if you are on windows 11)

**Comment by Roryplewes** [comment]
Unfortunately I am mac. Quite happy doing it the slow way though

**Comment by treee111** [comment]
@Roryplewes, thanks for opening the issue and having a nice conversation with @Ebe66 - thanks for helping out!
He anyway knows more about the OSM download than me ;-)
