### ISSUE TITLE
Two little documentation issues

### ISSUE THREAD

**Issue by siovene** [treee111/wahooMapsCreator#27]
The following page:

https://github.com/treee111/wahooMapsCreator/blob/develop/docs/QUICKSTART_MACOS.md

mentions "Install Osmfilter" twice as headers. The second one should be osmium-tool.

Additionally, it says to `apt install osmctools` but `apt` is not available on MacOS and that package is not available via `brew`.

**Comment by treee111** [comment]
Hi @siovene, thanks for your comments.
I made changes in the attached commit. You are invited to check if it is now clearer!

Could you use the tool successfully without installing osmctools/ osmconvert?

**Comment by siovene** [comment]
Hi @treee111. After a while I gave up, unfortunately. I wanted to use this tool because I had poor internet connection and couldn't download one of the official Wahoo maps, but the download worked in the end.

**Comment by treee111** [comment]
Hi @siovene, I know, in the beginning it is a little struggle to get everything going.
Glad, that the official download worked.

If you have the feeling that the maps are old and do not show relevant routes in your area you could give the tool another try ;)
